new attempt at GitHub action to render Rmd

diff --git a/.github/workflows/compile_rmarkdown.yml b/.github/workflows/compile_rmarkdown.yml
--- a/.github/workflows/compile_rmarkdown.yml
+++ b/.github/workflows/compile_rmarkdown.yml
@@ -1,44 +1,36 @@
-name: Compile R Markdown to HTML and PDF
-
+# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
 on:
   push:
-    branches:
-      - master  # Change to your repository's default branch
-    paths:
-      - "texor.Rmd"
+    paths: ['**.Rmd']
+
+name: render-rmarkdown
 
 jobs:
-  build:
+  render-rmarkdown:
     runs-on: ubuntu-latest
-
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v2
+      - name: Checkout repo
+        uses: actions/checkout@v3
+        with:
+          fetch-depth: 0
 
-    - name: Install dependencies
-      run: |
-        sudo apt-get update
-        sudo apt-get install -y pandoc texlive-latex-base texlive-fonts-recommended texlive-fonts-extra
+      - uses: r-lib/actions/setup-pandoc@v2
+      
+      - uses: r-lib/actions/setup-tinytex@v2
 
-    - name: Install R and packages
-      uses: r-lib/actions/setup-r@v1
-      with:
-        r-version: "release"  # Change to your desired R version
+      - uses: r-lib/actions/setup-r@v2
 
-    - name: Install R packages
-      run: |
-        R -e 'install.packages(c("rmarkdown"))'
-
-    - name: Compile R Markdown to HTML
-      run: R -e 'rmarkdown::render("texor.Rmd")'
-
-    - name: Compile R Markdown to PDF
-      run: R -e 'rmarkdown::render("texor.Rmd", "pdf_document")'
-
-    - name: Upload HTML and PDF
-      uses: actions/upload-artifact@v2
-      with:
-        name: compiled-files
-        path: |
-          texor.html
-          texor.pdf
+      - uses: r-lib/actions/setup-renv@v2
+      
+      - name: Render Rmarkdown files and Commit Results
+        run: |
+          RMD_PATH=($(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '[.]Rmd$'))
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f)' ${RMD_PATH[*]}
+          Rscript -e 'for (f in commandArgs(TRUE)) if (file.exists(f)) rmarkdown::render(f, "pdf_document")' ${RMD_PATH[*]}
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git commit ${RMD_PATH[*]/.Rmd/.md} -m 'Re-build Rmarkdown files' || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
